# -*- coding: utf-8 -*-
"""suude_yildiz_midterm.ipynb adlı dosyanın kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16tc7Fjqm9YbfvgAL0Luhv4TkZaQ_fCsr

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on Drive.
ex: atay_ilgun_MIDTERM.ipynb

Describe what ML is in 50 words.

Machine Learning is the way of creating generic algorithms which can give you useful informations about a group of data without writing any code. The algorithm can create its own logic by creating a pattern with the datas that you gave. Basically, Machine learning is the way that data is interpreted by an algorithm to create a pattern.

Give 3 examples of ML in practical use in todays world - also, meditate on how it is being utilised as well.

1.Recommendation Systems of Netflix, Spotify, Amazon, Youtube etc. 
2.Face Recognition system of Bank Applications 
3.Weather Forecast Applications 
4.Google Assistant (The personal assistant which can be used with many kind of smart devices, developed by Google)
5.Online Customer Help

In ML terminology what is an 'example', 'feature', 'label' and 'feature vector'?

1. Feature is basically the input and label is the output. For example, İf you are trying to predict the type of a dog, your input features can be length, color, weight etc. The label is the final choice of your inputs such as Golden, Chiwawa.
2. Feature vector is numeric representation of features. [150, 1, 0]
3. An example is a particular instance of data. It has two categories: unlabeled and labeled.

In 100 words meditate on how future advancements on AI could affect your work practice as a communication designer.

When I think in a Professional way and as a future user experience designer, I would say that I am very inspired by artifical intelligence and the concept of algorithm because it gives me a power to understand my users and their problems ( Like the system of Netflix, Spotify, Amazon etc.) In the future, the artifical intelligence can be very useful, if I would decide to make actual my own start up idea which is related to user experience. After I started this course, I also noticed that I have already been benefited from the artifical intelligence to make collaboration with my users (such as Google analytics)

Try to describe how you learn in algorithmic terms.

When I learn something new I basically take datas given by someone or something. Then I interpret that datas with my past experience. Lastly, I create something new as a ouput which is collaboration of my past experiences-patterns and the new datas given to me. In the context of machine learning, I can say that my brain is the machine here.

Create a python dictionary for your name surname and year of birth.
"""

a_dict1 = {'name':'suude', 'surname': 'yildiz', 'year of birth': '1996'}

a_dict1.keys()

a_dict1.values()

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

a = a_dict1['name']

if a[0] == a:
  print('my initial is a!')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

my_surname = a_dict1['surname']

if len(my_surname) % 3 == 0:
  print('it is divisible')
else:
  print('not divisible')

"""Change your year of birth to 2678."""

a_dict1['year of birth'] = 2678

print(a_dict1)

"""Create a loop that goes through 20 to 40 and prints out the numbers that are divisble by 5."""

list_1 = range(20,40)

for everynumber in list_1:
  if everynumber % 5 == 0:
    print(everynumber)

"""Check the PDF on the Drive and calculate the neurons. Put all neurons and weights in python and do the calculation with them."""

a = 0.87 
b = 0.12 
c = 0.62

x = 0.06 
y = 0.12 
z = 0.47

s = (a*x) + (b*y) + (c*z)

print(s)

s = (0.87*0.06) + (0.12*0.12) + (0.62*0.47)

print(s)

"""Using the code here:
https://github.com/anishathalye/neural-style
create a ***style transfer*** image.

Upload it along with this file.

You might need a file while doing this, it also is on the Drive!
"""